dist: bionic
language: node_js
node_js:
  - "10"
services:
  - postgresql
  - redis-server
addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
before_script:
  - sudo service postgresql restart
  - psql -c 'create database db_test;' -U postgres
  - psql -c "CREATE USER $NAME$USER;"
  - npm run init-test
